name: appcomics
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.6
  page_transition: ^2.0.9
  animated_bottom_navigation_bar: ^1.3.3
  firebase_database: any
  firebase_core: any
  cloud_firestore: any
  textfield_shadow: ^1.2.0
  sign_in_button: ^3.2.0
  social_login_buttons: ^1.0.7
  flutter_social_button: ^1.1.4+1
  scroll_page_view: ^1.0.2
  draggable_scrollbar: ^0.1.0
  group_button: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Line 29.png
    - assets/Gmail_icon 1.png
    - assets/facebook_icon.png
    - assets/Rectangle 19.png
    - assets/anh_mau_1.png
    - assets/anh_mau_2.png
fonts:
  - family: Schyler
    fonts:
      - asset: fonts/Schyler-Regular.ttf
      - asset: fonts/Schyler-Italic.ttf
        style: italic
  - family: Raleway
    fonts:
      - asset: fonts/Raleway-Regular.ttf
      - asset: fonts/Raleway-Italic.ttf
        style: italic
  - family: RobotoMono
    fonts:
      - asset: fonts/RobotoMono-Regular.ttf
      - asset: fonts/RobotoMono-Bold.ttf
        weight: 700
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Light.ttf
        weight: 300
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/OpenSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/OpenSans-MediumItalic.ttf
        weight: 500
      - asset: assets/fonts/OpenSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/OpenSans-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/OpenSans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/OpenSans-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/OpenSans-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        weight: 800
        style: italic
  - family: AlegreyaSans
    fonts:
      - asset: assets/fonts/AlegreyaSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/AlegreyaSans-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/AlegreyaSans-Light.ttf
        weight: 300
      - asset: assets/fonts/AlegreyaSans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/AlegreyaSans-Regular.ttf
      - asset: assets/fonts/AlegreyaSans-Italic.ttf
        style: italic
      - asset: assets/fonts/AlegreyaSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/AlegreyaSans-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/AlegreyaSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/AlegreyaSans-Black.ttf
        weight: 900
      - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
        weight: 900
        style: italic
