// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKXI6Srn_R7W5XCShk2kRtOt-Yn_Kk-yA',
    appId: '1:792241270913:web:28240d1c6d36c84b655d80',
    messagingSenderId: '792241270913',
    projectId: 'comicreader-680db',
    authDomain: 'comicreader-680db.firebaseapp.com',
    storageBucket: 'comicreader-680db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyLHFgs6hlmY26KZka0fFbXCNxhBBfiM',
    appId: '1:792241270913:android:03698199776daa62655d80',
    messagingSenderId: '792241270913',
    projectId: 'comicreader-680db',
    storageBucket: 'comicreader-680db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBflLa6rvKrMtBWccTdGBPV328SiW3BNec',
    appId: '1:792241270913:ios:b04c45cfdb64769b655d80',
    messagingSenderId: '792241270913',
    projectId: 'comicreader-680db',
    storageBucket: 'comicreader-680db.appspot.com',
    iosBundleId: 'com.example.comicReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBflLa6rvKrMtBWccTdGBPV328SiW3BNec',
    appId: '1:792241270913:ios:b04c45cfdb64769b655d80',
    messagingSenderId: '792241270913',
    projectId: 'comicreader-680db',
    storageBucket: 'comicreader-680db.appspot.com',
    iosBundleId: 'com.example.comicReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKXI6Srn_R7W5XCShk2kRtOt-Yn_Kk-yA',
    appId: '1:792241270913:web:dc737f570317decc655d80',
    messagingSenderId: '792241270913',
    projectId: 'comicreader-680db',
    authDomain: 'comicreader-680db.firebaseapp.com',
    storageBucket: 'comicreader-680db.appspot.com',
  );
}
